README.md
packages/graphql-armor/src/index.ts

This pull request provides support for adding two additional security parameters provided by Apollo: `allowBatchedHttpRequests`for preventing batched queries, and `debug` for removing stacktraces.
With this change,
```
const server = new ApolloServer({
...armor.protect()
})
```
will set both `allowBatchedHttpRequests` and `debug` to `false`.
Here is the docs for these two parameters:
- [allowBatchedHttpRequests](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#allowbatchedhttprequests)
- [debug](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#debug)

feat(graphql-armor): add stacktraces and batched queries proposals

---

packages/graphql-armor/src/apollo/protections/block-field-suggestion.ts
packages/graphql-armor/src/config.ts
packages/graphql-armor/src/envelop/protections/block-field-suggestion.ts
packages/plugins/block-field-suggestions/README.md
packages/plugins/block-field-suggestions/src/index.ts
packages/plugins/block-field-suggestions/test/index.spec.ts

Adding and optional parameter to the block-field-suggestion plugin to replace the current `[Suggestion message hidden by GraphQLArmor]` in case users would like to obscure their usage of Armor for security. This parameter is also added to the Apollo and Envelop Armor sections. 
https://github.com/Escape-Technologies/graphql-armor/issues/116

Configure suggestion mask string

---

.changeset/honest-trainers-pretend.md
examples/yoga/test/index.spec.ts
packages/plugins/character-limit/src/index.ts
packages/plugins/character-limit/test/index.spec.ts

Currently the character limit plugin doesn't work in envelop.
The plugin is attempting to read the query from the context object.  This assumption isn't documented, or required.
Updated the plugin to instead replace the parse function and check query length when it attempts to parse the query into a Document.  This has the added benefit of failing during the parse step, allowing yoga to infer that the request was invalid and set the status code to 400.

fix(character-limit): block requests before parsing

---

.changeset/gentle-ants-grin.md
packages/plugins/max-aliases/src/index.ts
packages/plugins/max-aliases/test/index.spec.ts

Currently, field aliases within fragment spreads are not counted. This PR addresses this.

fix: count field alias in fragment spread

---

examples/nestjs/package.json
package.json
packages/graphql-armor/package.json
packages/plugins/block-field-suggestions/package.json
packages/plugins/character-limit/package.json
packages/plugins/cost-limit/package.json
packages/plugins/document-token-limit/package.json
packages/plugins/max-aliases/package.json
packages/plugins/max-depth/package.json
packages/plugins/max-directives/package.json
yarn.lock

Drop `apollo-server` from peerDependencies in benefit of `apollo-server-core`/`apollo-server-types`.
Every `apollo-server-*` extension relies on `apollo-server-core`.
`apollo-server` is not used by `apollo-server-koa` for example.
---
Also drop unnecessary `@types/node`

chore(deps)/drop-apollo-server+typesnode

---

packages/plugins/document-token-limit/src/index.ts

Time parsing token has been proven quadratic, here 2000 make tests 22 seconds against 7seconds for 1000.
A default value of 1000 tokens should be enough for most usage.

fix(document-token-limit): reduce default value

---

.changeset/config.json
.vscode/launch.json
examples/apollo/README.md
examples/apollo/package.json
examples/nestjs/README.md
examples/nestjs/package.json
examples/yoga/README.md
examples/yoga/package.json
yarn.lock

- Remove branding from examples
This will make examples easier to access using CLI.
This was not sustainable as we don't publish theses packages anyway.

chore(examples)/non-branded-names

---

services/docs/docs/configuration/examples.md
services/docs/package.json
yarn.lock

This MR add two examples in the documentation, configuration part.
-  Make GraphQL Armor inoffensive
-  Observe rejected requests

chore(docs): add config examples

---

install-dev.sh
packages/plugins/max-tokens/src/index.ts

Running install-dev.sh is quite a ride!
<details>
<summary>Logs</summary>
```console
Installing development tools...
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @docsearch/react@npm:3.2.1 [9c7a7] doesn't provide @algolia/client-search (p9aa09), requested by @algolia/autocomplete-preset-algolia
➤ YN0002: │ ts-node-dev@npm:2.0.0 [a7c7e] doesn't provide @types/node (p5d27c), requested by ts-node
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 254ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs@npm:15.4.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:17.5.1 can't be found in the cache and will be fetched from the …
```

chore: fixed install-dev.sh

---

services/docs/docs/plugins/max-aliases.md
services/docs/docs/plugins/max-tokens.md

This PR makes two minor corrections to the plugin documentation.
1. In Max Aliases, the comment mentioned "Directives" rather than "Aliases"
2. In Max Tokens, comments and code examples reference "max-depth" rather than "max-tokens"

docs(plugins): corrects mention of directives/tokens threshold

---

services/docs/docs/plugins/cost-limit.md

This PR corrects the Cost Limit Plugin docs where the config option incorrectly referenced `maxAliases` instead of `costLimit`.

docs(plugins): correct cost limit option

---

.changeset/beige-rockets-wonder.md
packages/graphql-armor/README.md

When the `graphql-armor-cost-limit` was updated, the main `graphql-armor` package didn't seem to publish:
```
16
🦋  info npm info @escape.tech/graphql-armor
17
🦋  info npm info @escape.tech/graphql-armor-block-field-suggestions
18
🦋  info npm info @escape.tech/graphql-armor-character-limit
19
🦋  info npm info @escape.tech/graphql-armor-cost-limit
20
🦋  info npm info @escape.tech/graphql-armor-max-aliases
21
🦋  info npm info @escape.tech/graphql-armor-max-depth
22
🦋  info npm info @escape.tech/graphql-armor-max-directives
23
🦋  info npm info @escape.tech/graphql-armor-max-tokens
24
🦋  info npm info @escape.tech/graphql-armor-types
25
🦋  warn @escape.tech/graphql-armor is not being published because version 1.6.0 is already published on npm
```
This PR does two things:
1 - has some minor …

chore: upgrades graphql-armor-cost-limit plugin to 1.7.0

---

.changeset/tough-weeks-yawn.md
.changeset/wicked-shrimps-arrive.md
examples/apollo/test/index.spec.ts
examples/yoga/test/index.spec.ts
packages/plugins/cost-limit/src/index.ts
packages/plugins/cost-limit/test/index.spec.ts
packages/plugins/max-aliases/src/index.ts
packages/plugins/max-aliases/test/index.spec.ts
packages/plugins/max-depth/src/index.ts
packages/plugins/max-depth/test/index.spec.ts

This MR handle the recursive fragment problem gracefully and prevent `max recursion error` to be thrown.
This affect:
- cost-limit
- max-directives
- max-aliases

fix: graceful recursive fragments

---

.changeset/six-readers-juggle.md
examples/apollo-v3/test/index.spec.ts
examples/apollo/test/index.spec.ts
examples/yoga/test/index.spec.ts
packages/plugins/cost-limit/src/index.ts
packages/plugins/cost-limit/test/index.spec.ts
packages/plugins/max-aliases/src/index.ts
packages/plugins/max-depth/src/index.ts
packages/plugins/max-directives/src/index.ts

Fix fragments visitor where inline fragments were inferred as recursive ones.
This breaking behavior has been introduced in a previous release patching recursive fragment.
This MR address both the fragment cache calculation for visitor plugins and make the `fragmentRecursion` cost deprecated.
We will prefer handling recursive fragments check through GraphQL JS.
Thanks @simoncrypta @dthyresson for the catch.

fix: inline fragments visitor

---

.changeset/long-cougars-warn.md
.changeset/modern-toys-own.md
.github/workflows/ci.yaml
package.json
packages/graphql-armor/package.json
packages/plugins/block-field-suggestions/package.json
packages/plugins/character-limit/package.json
packages/plugins/cost-limit/package.json
packages/plugins/max-aliases/package.json
packages/plugins/max-depth/package.json
packages/plugins/max-directives/package.json
packages/plugins/max-tokens/package.json

In #418, envelop has fixed its minimal version to node 16.
[Node 14 has reached its EOL](https://github.com/nodejs/release#release-schedule), we are dropping its support too.

chore: drop node 14 and require node 16 or higher

---

.changeset/weak-dolphins-shout.md
examples/apollo-v3/test/index.spec.ts
examples/apollo/test/index.spec.ts
examples/yoga/test/index.spec.ts
packages/plugins/max-tokens/src/index.ts
packages/plugins/max-tokens/test/index.spec.ts

The max tokens plugins error message includes a found count that is always +1 of the allowed count because it stops parsing the document after it exceeds the allowed count. 
We could obviously parse the entire document and return the total count but this seems like wasted cycles to calculate the total number of tokens.

Remove the found count from the max tokens plugin. 

---

.changeset/many-phones-tan.md
packages/plugins/max-depth/src/index.ts
packages/plugins/max-depth/test/index.spec.ts
services/docs/docs/plugins/max-depth.md

#431
Provides a new option to the Max Depth plugin - `flattenFragments`, defaulted to `false`.
When set to `true`, the max depth plugin will ignore nodes of kind `INLINE_FRAGMENT` and `FRAGMENT_SPREAD` when performing the depth calculation, so that the depth will be considered the same regardless of the usage of fragments.

feat: add flattenFragments option to max-depth

---

.changeset/cyan-crews-do.md
packages/plugins/max-aliases/src/index.ts
packages/plugins/max-aliases/test/index.spec.ts

This PR aims to add an allow list of alias names that are not counted in the number of aliases.
To provide a more robust way of keeping track of cached entities, the `@envelop/response-cache` plugin rely on aliases added server side to every query documents. This allows us to ensure we have access to `__typename` and `id` of each composite object selected in the query.
But unfortunately, this doesn't play nicely with the `max-aliases` plugin, since any query will quickly use a lot of aliases.
I have though about another solution: an allow list of field that can always be aliased. But I think that this is way less safe because someone could add any number of aliases, while the proposed solution only opens the possibility to add defined aliases to every selection set.

feat(max-aliases): add an allow list of unlimited aliases name

---

packages/plugins/max-aliases/src/index.ts
packages/plugins/max-aliases/test/index.spec.ts
services/docs/docs/plugins/max-aliases.md

Closes #738, supersedes #766
There is a GraphQL vulnerability related to allowing an unlimited number of aliases of `__typename` - an attacker can craft a query that consists of tens of thousands of aliases, like `{"query": "query aliasOverLoad { alias0: __typename alias1: __typename alias2: __typename alias3: __typename alias4: __typename alias5: __typename <...thousands more> }"}` and can be a way to bypass authentication on the API because it does not hit any resolvers. With enough simultaneous queries like this it can fairly easily bring down a server.
In #468 the behavior of the max aliases plugin was modified to permanently omit aliases of `__typename` from the alias count. This PR builds on those changes by setting the default value of `allowList` to `["__typename"]` so that …

fix: add __typename to the default value of allowList

---

packages/plugins/cost-limit/src/index.ts
packages/plugins/cost-limit/test/index.spec.ts

This PR fixes a bypass to the cost-limit plugin (in default settings) by skipping only nodes of type `Field` when `ignoreIntrospection` is set.
This will fix the following type of bypasses:
```gql
query  {
...__schema
}
fragment __schema on Query {
books {
title
author
}
}
```
```gql
query __schema {
books {
title
author
}
}
```

fix: cost-limit ignore only Field Node named `__schema`

---

.changeset/rude-laws-yawn.md
packages/graphql-armor/CHANGELOG.md
packages/graphql-armor/package.json
packages/plugins/cost-limit/CHANGELOG.md
packages/plugins/cost-limit/package.json
yarn.lock

Fixes https://github.com/Escape-Technologies/graphql-armor/security/dependabot/125

chore: bump gql armor to 3.1.4 with cost-limit bump

---

.changeset/rude-laws-yawn.md
packages/graphql-armor/CHANGELOG.md
packages/graphql-armor/package.json
packages/plugins/cost-limit/CHANGELOG.md
packages/plugins/cost-limit/package.json
yarn.lock

Reverts Escape-Technologies/graphql-armor#791 due to release process

Revert "chore: bump gql armor to 3.1.4 with cost-limit bump"
